[database]
addr = "127.0.0.1"              # 数据库地址
port = 5432                     # 端口
name = "JsutOJ"                 # 数据库名称
username = "JsutOJAdmin"        # 数据库用户
password = "jsutojadmin"        # 数据库密码

[root]                          # OJ 超级管理员初始化
stu_id = "2024243108"           # 学号
username = "tim"                # 用户名, 作为登录凭据
nickname = "孙笑川258"           # 昵称, 外部显示
password = "1145141919810"      # 密码, 保存将以 md5 形式保存
email = "qjtykr65536@gmail.com" # 邮箱

[limit]
complie_cpu = 0.5               # CPU 限制
complie_memory = 1024           # 内存限制(MB)
complie_time = 10               # 时间限制
output_limit = 33554432         # 输出超限阈值
checker_max_score = 240         # checker最大分数
checker_time_limit = 10         # checker时间限制
checker_memory_limit = 1024     # checker内存限制