[database]
addr = "127.0.0.1"
port = 5432
name = "JsutOJ"
username = "JsutOJAdmin"
password = "jsutojadmin"

[root]
stu_id = "2024243108"
username = "tim"
nickname = "孙笑川258"
password = "1145141919810"
role = "admin"
email = "qjtykr65536@gmail.com"

